version: "3.9"
services:
  bot:
    build: .
    restart: always
    command: python main.py
    env_file:
      - .env
    ports:
      - 8000:5000
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:14.5-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"